config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#index'
  delete '/logout', to: 'sessions#destroy'
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/failure', to: 'sessions#auth_failure'

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  provider   :string
#  uid        :string
#  name       :string
#  location   :string
#  image_url  :string
#  url        :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
class User < ActiveRecord::Base
    class << self
      def from_omniauth(auth_hash)
        user = find_or_create_by(uid: auth_hash['uid'], provider: auth_hash['provider'])
        user.name = auth_hash['info']['name']
        user.location = get_social_location_for user.provider, auth_hash['info']['location']
        user.image_url = auth_hash['info']['image']
        user.url = get_social_url_for user.provider, auth_hash['info']['urls']
        user.save!
        user
      end
  
      private
  
      def get_social_location_for(provider, location_hash)
        case provider
          when 'linkedin'
            location_hash['name']
          else
            location_hash
        end
      end
  
      def get_social_url_for(provider, urls_hash)
        case provider
          when 'linkedin'
            urls_hash['public_profile']
          else
            urls_hash[provider.capitalize]
        end
      end
    end
  
  
  end
  

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  helper_method :current_user
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def index
    end
  end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def create
      #render text: request.env['omniauth.auth'].to_yaml and return
      begin
        @user = User.from_omniauth(request.env['omniauth.auth'])
        session[:user_id] = @user.id
        flash[:success] = "Bienvenido, #{@user.name}!"
      rescue
       flash[:warning] = "There was an error while trying to authenticate you..."
      end
      redirect_to root_path
    end
  
    def destroy
      if current_user
        session.delete(:user_id)
        flash[:success] = 'See you!'
      end
      redirect_to root_path
    end
  
    def auth_failure
      redirect_to root_path
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Inicio se Sesión con Google</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="g-signin2" data-onsuccess="onSignIn"></div>
<nav class="navbar navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <%= link_to 'Social Freak', root_path, class: 'navbar-brand' %>
    </div>
    <div id="navbar">
      <% if current_user %>
        <ul class="nav navbar-nav pull-right">
          <li><%= image_tag current_user.image_url, alt: current_user.name %></li>
          <li><%= link_to 'Cerrar sesión', logout_path, method: :delete %></li>
        </ul>
      <% else %>
        <ul class="nav navbar-nav">
          <li><%= link_to 'Twitter', '/auth/twitter' %></li>
          <li><%= link_to 'Facebook', '/auth/facebook' %></li>
          <li><%= link_to 'Google+', '/auth/google' %></li>
          <li><%= link_to 'LinkedIn', '/auth/linkedin' %></li>
        </ul>
      <% end %>

    </div>
  </div>
</nav>

<div class="container">
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>">
      <%= value %>
    </div>
  <% end %>

  <%= yield %>
</div>


</body>
</html>

app/views/pages/_welcome.html.erb
<div class="jumbotron">
  <h1>Welcome!</h1>
  <p>Authenticate via one of the social networks to get started.</p>
</div>

app/views/pages/index.html.erb
<% if current_user %>
  <div class="page-header">
    <h1>Datos de la sesión iniciada:</h1>
  </div>
  <div class="panel panel-default">
    <div class="panel-body">
      <ul>
        <li><strong>Nombre:</strong> <%= current_user.name %></li>
        <li><strong>Provider:</strong> <%= current_user.provider %></li>
        <li><strong>uID:</strong> <%= current_user.uid %></li>
        <li><strong>Avatar URL:</strong> <%= current_user.image_url %></li>
        <li><strong>URL:</strong> <%= current_user.url %></li>
      </ul>
    </div>
  </div>
<% else %>
  <%= render 'welcome' %>
<% end %>